version: '3'

#задать параметры сети для контейнеров
networks:
  mynetwork:
    ipam:
      config:
      - subnet: 172.16.1.0/24

services:
  nginx:
    container_name: ngx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./srv/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./srv/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./srv/nginx/logs:/var/log/nginx
      - ./srv/www/html:/var/www
    #перезагрузка контейнера при ошибке
    restart: always
    #настрофка сети контейнера 
    environment:  
      - TZ
      - IP_BROKER=mqtt
      - DOCKER=true
      - PORT=1880
    hostname: hostnginx
    networks:
      mynetwork:
        ipv4_address: 172.16.1.3

  apache:
    container_name: apache
    image: ohmy/apache-php7.2-prod
    ports:
      - 8080:8080
    volumes:
      - ./srv/www/html:/var/www
      - ./srv/apache/conf/apache2.conf:/etc/apache2/apache2.conf
      - ./srv/apache/conf/ports.conf:/etc/apache2/ports.conf
      - ./srv/apache/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./srv/apache/logs:/var/log/apache2
    environment:
      - TZ
      - IP_BROKER=mqtt
      - DOCKER=true
      - PORT=1880
    hostname: hostapache
    networks:
      mynetwork:
        ipv4_address: 172.16.1.4


  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ
      - IP_BROKER=mqtt
      - DOCKER=true
      - PORT=1880
    hostname: hostmysql
    networks:
      mynetwork:
        ipv4_address: 172.16.1.5